### PR TITLE
Eventpool draft

### PR DESCRIPTION
**Pull request by CurlyMoo**

### CODE REVIEW

**Comment by CurlyMoo** [comment]
I will start with the first libuv-extra. My basic observer pattern in C based on libuv. In reality what i call eventpool contains a lot more code. I've also added a socket non-blocking IO abstraction in it in pilight based on uv_poll_t that allows me to natively use SSL with libuv, but i want to focus on this functionality first.

I've also started with this codebase, because all my other socket modules depend on that extended eventpool.

And as you will read, naming is hell for programmers, so probably we can will a great deal there as well :smile:

Also, i'm fully ready for that discussion!

**Comment by CurlyMoo** [comment]
So, any comments on this first attempt?

**Comment by bnoordhuis** [comment]
Hi, and sorry for the delay.  I only looked at this briefly (also because the idea is that this repo is only lightly reviewed by libuv maintainers) but what stands out to me is this:

1. The style should preferably follow the main libuv repo.  Not a blocker, just a good thing.

2. I don't think we'd accept code that's under a different license than libuv itself (MPL vs MIT.)

**Comment by CurlyMoo** [comment]
> also because the idea is that this repo is only lightly reviewed by libuv maintainers

We've discussed that we would use a first PR to start the discussion. So let's discuss.

> The style should preferably follow the main libuv repo. Not a blocker, just a good thing.

First conclusion from the discussion:

1. The `CONTRIBUTING.md` should be copied from libuv to this repository.

> I don't think we'd accept code that's under a different license than libuv itself (MPL vs MIT.)

That's clearly something i want to discuss more, because i don't like BSD (type) licenses and i don't like GPL type licenses either for the obvious reasons.

**Comment by CurlyMoo** [comment]
Any interest in actually starting a discussion here or else i will withdraw my PR.

**Pull request closed without merging**
